### ISSUE TITLE
CSV is deleted before downloaded

### ISSUE THREAD

**Issue by kesselb** [yii2tech/csv-grid#13]
Homestead (Vagrant-Box from Laravel) with PHP7.1 running HumHub.

`$exporter = new CsvGrid(['dataProvider' => $dataProvider, 'columns' => ['id', 'username']]);`
`return $exporter->export()->send('my.csv');`

I would like to send the generated csv instead of saving it. Unfortunately this exceptions happens:  `unlink(/code/humhub/protected/runtime/csv-grid/15157521565a588adcbf03e8.01521473/data-001.csv): Text file busy`

yii\web\Response->sendFile open the csv with 'rb' and locks the file until the generate response is sent. But before the response is sent (and the file is unlocked) ExportResult->__destruct is called and tries to delete the locked file which leads to this exception.

Maybe this issue is related to my configuration. I could fix it by changing the ExportResult->send like this:
`$content =  file_get_contents($this->getResultFileName());`
`return Yii::$app->getResponse()->sendContentAsFile($content, $name, $options);`

**Comment by kesselb** [comment]
I may found another solution which fits better than file_get_contents ;-) 

Add to ExportResult->send() before return. `Yii::$app->getResponse()->on(Response::EVENT_AFTER_SEND, [$this, 'delete']);`

Than there is a reference to $this and __destruct is not called to early. After response->send() delete is called and folder is removed.

**Comment by klimov-paul** [comment]
Resolved by commit 836e71ead0706a4645708e6f85366aea4d162ced
