### ISSUE TITLE
Memory Exhausted on only 6000 rows

### ISSUE THREAD

**Issue by friek108** [yii2tech/csv-grid#16]
I'm receiving a memory exhausted on about 6000 rows, 2000 seems to work ok (have about 20 columns in the csv). I have 128mb of php memory and the batch commands are executing successfully when I look through the log.

Should this be happening? The docs seem to suggest I could export 30k, even 60k records with no issues and the only reason to be using document splitting would be if it exceeded Excel's max rows. (Thanks for the great extension by the way)

**Comment by klimov-paul** [comment]
Unable to reproduce.

Following code:

```php
var_dump(memory_get_usage());

$exporter = new CsvGrid([
    'query' => VehicleTelemetry::find(), // 39610 rows
    'batchSize' => 200,
    'columns' => [
        [
            'attribute' => 'id',
            'header' => 'ID',
        ],
        ...
    ],
]);
$exporter->export()->saveAs('@runtime/test.csv');

var_dump(memory_get_usage());
var_dump( memory_get_peak_usage());

exit;
```

outpust:

```
int 4000512

int 4362936

int 5973104
```

Make sure you have setup `CsvGrid::$bacthSize` correctly and search your code for memory leaks like using static variables, global cache and so on.

**Comment by ettolo** [comment]
Hi,
the code you provided should export all the 39610 records or only 200?
In my test it only export 200 rows... is this correct?
Should I use some sort of cycle to output all the records?
