### ISSUE TITLE
Export CSV as a Row wise header data instead of column wise.

### ISSUE THREAD

**Issue by PayalChauhan** [yii2tech/csv-grid#17]
I am doing export of csv file using Yii2 PHP Framework.
By using CSV-grid package i can able to do exporting of csv file as a column wise.
I want to export CSV as a Row wise using "Pivot Table" options into CSV.
I am unable to do that so, please help me.

**Comment by klimov-paul** [comment]
Architecture of this extension does not allow this, as `CsvGrid` writes dataest to the file row by row.
You should create your own solution for your task.
