### ISSUE TITLE
Calling unknown method: yii\grid\SerialColumn::renderHeaderCellContent()

### ISSUE THREAD

**Issue by goke-epapa** [yii2tech/csv-grid#2]
I get this error when I try to pass a columns array with a SerialColumn.

The `renderHeaderCellContent` method is a protected method in the parent class `Column`, so it's not accessible outside the child class `SerialColumn`.

```
...
 'columns' => [
                ['class' => SerialColumn::className(), 'header' => 'S/N'],
                [
                    'attribute' => 'attribute_name',
                ]
            ],
...
```

This code snippet also causes the same error

```
$serialColumn = new SerialColumn();
$serialColumn->renderHeaderCellContent();
```

I think a solution to this would be to create a SerialColumn that exposes the renderHeaderCellContent method used in the `composeHeaderRow` in the `CsvGrid` class and I have created a pull request here - https://github.com/yii2tech/csv-grid/pull/3

PHP Version: 5.5.36
Great library you have here 👍

**Comment by klimov-paul** [comment]
Resolved by commit aff458860fe62df4f0b78005efe9c4b1384128ed
