### ISSUE TITLE
Time to export 3200 records

### ISSUE THREAD

**Issue by ettolo** [yii2tech/csv-grid#20]
Hi,
is it normal it gets at least 4 minutes to export 3200 rows?
Pagesize is set to 2000, resulting CSV filesize is 989KB
What can I do to speed up the process?

**Comment by klimov-paul** [comment]
Unable to reproduce

```php
var_dump(Weather::find()->count()); // output: int 28772

        $beginTime = microtime(true);

        $exporter = new CsvGrid([
            'query' => Weather::find(),
            'batchSize' => 400,
            'columns' => [
                [
                    'attribute' => 'id',
                    'header' => 'ID',
                ],
                // ...
            ],
        ]);
        $exporter->export()->saveAs('@runtime/test.csv');

        $endTime = microtime(true);
        var_dump($endTime - $beginTime); // output: float 5.0191979408264
```

Check your application logs. Make sure you do not use lazy-loading relation data during the export, ActiveRecord event handlers does not perform any significant actions and so on.

**Comment by ettolo** [comment]
Thank you.
My table does not have any relation and no event
I tryied with
`
$exporter = new CsvGrid([
            'dataProvider' => new ActiveDataProvider([
                'query' => StockEstesa::find(),
                'pagination' =>['pageSize' => 2000,]
            ]),
        ]);
`
And it takes 4 minutes, no matter what i set in pagesize
I tryied with
`$exporter = new CsvGrid([
                'query' => StockEstesa::find(),
                'batchSize' => 400,
        ]);`
and it takes 5 seconds... but exports only 400 rows
