### ISSUE TITLE
long number result for export csv and read by MS Excel

### ISSUE THREAD

**Issue by krissss** [yii2tech/csv-grid#23]
# test code
```php
$exporter = new CsvGrid([
    'dataProvider' => new ArrayDataProvider([
        'allModels' => [
            [
                'name' => 'length14',
                'number' => '01234567890123',
            ],
            [
                'name' => 'length15',
                'number' => '012345678901234',
            ],
            [
                'name' => 'length16',
                'number' => '0123456789012345',
            ],
            [
                'name' => 'length17',
                'number' => '01234567890123456',
            ],
            [
                'name' => 'length18',
                'number' => '012345678901234567',
            ],
        ],
    ]),
    'columns' => [
        [
            'attribute' => 'name',
        ],
        [
            'attribute' => 'number',
        ],
    ],
]);
return $exporter->export()->send('test.csv');
```

# result csv
```
"Name","Number"
"length14","01234567890123"
"length15","012345678901234"
"length16","0123456789012345"
"length17","01234567890123456"
"length18","012345678901234567"
```
# read by MS Excel
![image](https://user-images.githubusercontent.com/10680903/45581860-9827ec00-b8d8-11e8-89c2-0cead5d66f83.png)

# error
Records is right in csv file, but error in MS Excel.
When number length is larger than 16, MS Excel will truncation it. You can see it in `length17` and `length18`, they end of `0`

**Comment by krissss** [comment]
# solve
https://github.com/yii2tech/csv-grid/blob/1cfc9b40e5b47afa4dc16e74e1607d560c8b90d6/src/CsvGrid.php#L450

with `"\t"` end
like:
```php
$cells[] = $column->renderDataCellContent($model, $key, $index) . "\t";
```

I think you can add a config attribute to switch this.

**Comment by klimov-paul** [comment]
Rejected.
This is excel specific problem, and it can be fixed in different ways. For example: you may switch the data type for the entire column to "text" instead of "number".

You can create a special format for you case and apply it using [CsvGrid::$formatter](https://github.com/yii2tech/csv-grid/blob/master/src/CsvGrid.php#L53), or use [DataColumn::$value](https://github.com/yii2tech/csv-grid/blob/master/src/DataColumn.php#L51) to modify the cell content.
