### ISSUE TITLE
Setting 200 as pagesize in ActiveDataProvider results in duplicated CSV records

### ISSUE THREAD

**Issue by ettolo** [yii2tech/csv-grid#24]
Hi, i found a problem.

searchModel:
```
        $dataProvider = new ActiveDataProvider([
            'query' => Stock::find(),
            'pagination' => ['pageSize' => 200,]
        ]);
```
Controller:
```
 $searchModel = new StockSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $exporter = new CsvGrid([
            'dataProvider' => $dataProvider,
            'columns' => [
                'PART_NUMBER',
                'QTY',
            ],
        ]);
        $filename = 'Stock';
        $date = new \DateTime();
        $date->modify("+2 hours");
        $date = Yii::$app->formatter->asDatetime($date,'yyyy-MM-dd_HH-mm-ss');
        return $exporter->export()->send($filename.'_'.$date.'.csv');

```
If I set pagesize to 200 I found duplicated and overwritten records in exported CSV. 
The number of rows is the same of the table in database (5800 records more or less) so some rows get overwritten in CSV.
If I remove pagesize the export is correct (but takes a long time)
If I put 100 as pagesize it's everything ok.
I think this is very dangerous! Any hint?
Thank you!

**Comment by ettolo** [comment]
No, I made some other tests with simplified code, found duplicated records also with pagination set as 100:

```
public function actionExportStockCsv()
    {      
        $exporter = new CsvGrid([
            'dataProvider' => new ActiveDataProvider([
                'query' => Stock::find(),
                'pagination' => [
                    'pageSize' => '100', // export batch size
                ],
            ]),
            'columns' => [
                'PART_NUMBER',
                'num_serie',
                'DESCRIPTION',
                'QTY',
            ],
        ]);
        $filename = 'Stock';
        $date = new \DateTime();
        $date = Yii::$app->formatter->asDatetime($date,'yyyy-MM-dd_HH-mm-ss');
        return $exporter->export()->send($filename.'_'.$date.'.csv');
    }
```
Could the problem be derived from the fact I don't have a primary key in the table (it is a view)?

**Comment by klimov-paul** [comment]
Using pagination mechanism for entire table rows extraction may produce unexpected results in some cases.
You should either use "batch" approach or setup an explicit sort order for the data via `Query::orderBy()`.

**Comment by ettolo** [comment]
@klimov-paul Thank you for your support!

**Comment by mailgagannow** [comment]
i am using batch size 5 it's still give me all records
