### ISSUE TITLE
Issue with multiple sheet in single csv

### ISSUE THREAD

**Issue by pawansgi92** [yii2tech/csv-grid#25]
I am unable to add the multiple sheet in single csv.

 $file_name ='all_'.date('Y-m-d h:i:s').'.csv';
       $exporter = new CsvGrid([
            'dataProvider' => new ArrayDataProvider([
                'allModels' =>$newUserData['all'],
            ]),
        ]);
       $exporter->export()->send($file_name);

is their any other way to add multiple sheet

**Comment by klimov-paul** [comment]
CSV file format does not support multiple sheets.
