### ISSUE TITLE
add option to output attribute names instead of labels

### ISSUE THREAD

**Issue by RaiMX** [yii2tech/csv-grid#26]
Can you please add an option so that resulting csv file would have attributes as headers, instead of labels or "converted" to regular words.
For example:
attributes are: id, first_name, last_name
currently the output csv will have headers as: Id, First Name, Last Name
desired headers: id, first_name, last_name

**Comment by klimov-paul** [comment]
Rejected.
You can setup any colunm header using [Column::$header](https://github.com/yii2tech/csv-grid/blob/master/src/Column.php#L27).
