### ISSUE TITLE
CSV Grid causes error upon export()->saveAs()

### ISSUE THREAD

**Issue by chaslain** [yii2tech/csv-grid#28]
Occurs when a csv grid is completely empty (empty dataprovider) and headers are set to hidden.

### What steps will reproduce the problem?
Load dataprovider with empty set, load this provider into a csvgrid, and set the showHeader property to false.
### What is the expected result?
Empty csvgrid 
### What do you get instead?
Error 500: no such file or directory

**Comment by klimov-paul** [comment]
Resolved by commit 4f67908d5c77e15f103415b0aa9546022d3a2840
