### ISSUE TITLE
Yii2 csvgrid not supporting special character such as ">" ,"<" ,": "

### ISSUE THREAD

**Issue by pawansgi92** [yii2tech/csv-grid#30]
### What steps will reproduce the problem?

I simply fetch the result from database write into csv file

### What is the expected result?
Expected result: > 5
upcoming result: &lt;5

### Additional info

| Q                     | A
| --------------------- | ---
| This Package Version  | 1.0.1
| Yii Framework Version | 2.13
| PHP version           | 7.0.33
| Operating system      | Ubuntu 16

**Comment by klimov-paul** [comment]
Sorry, but I can not understand the problem from the such description.
Try to provide the code snippet or something.

**Comment by klimov-paul** [comment]
Closed since no clear description provided.

**Comment by pawansgi92** [comment]
@klimov-paul  ..

I want print in greater than and less than sings in CSV file. But if I pass i will get corrupted value

**Comment by klimov-paul** [comment]
This might be related to #18.
You should use the latest version of this package, e.g. 1.0.5 instead of 1.0.1.
