### ISSUE TITLE
Not compatible with GridView

### ISSUE THREAD

**Issue by Sarke** [yii2tech/csv-grid#33]
### What steps will reproduce the problem?
Use something like `contentOptions` in the columns.

### What is the expected result?
That I would be able to use the same config I do for `yii\web\GridView` so that I could easily output a CSV with the same columns and formatting.

### What do you get instead?
Error, `Setting unknown property: yii2tech\csvgrid\DataColumn::contentOptions`

### Additional info
Why are you defining your own `DataColumn` instead of extending the `yii\grid\DataColumn`?

| Q                     | A
| --------------------- | ---
| This Package Version  | 1.0.5
| Yii Framework Version | 2.0.42.1
| PHP version           | 8.0.5
| Operating system      | Linux

**Comment by klimov-paul** [comment]
There can not be any support for `Column::$contentOptions` as it used for HTML tag attribute rendering, while CSV format does not use tag-based markup.

**Comment by Sarke** [comment]
I think accepting it but ignoring it would be an option, so it works with the same config as for GridView.
