### ISSUE TITLE
Crashes when query returns no results and csv headers are enabled

### ISSUE THREAD

**Issue by ptheofan** [yii2tech/csv-grid#34]
When Query returns no results and CSV export show header is enabled it crashes because columns are not initialized yet.

The while loop never runs, columns are never initialized (but a CSV file has already been created)
https://github.com/yii2tech/csv-grid/blob/6d10b2b7590affd95ae2bacf20562c24d59d0ece/src/CsvGrid.php#L296

Thus this line allows the execution to continue (file is allocated but no data exist)
https://github.com/yii2tech/csv-grid/blob/6d10b2b7590affd95ae2bacf20562c24d59d0ece/src/CsvGrid.php#L335

Tries to render header rows while columns have not been initialized.
https://github.com/yii2tech/csv-grid/blob/6d10b2b7590affd95ae2bacf20562c24d59d0ece/src/CsvGrid.php#L340

**Comment by klimov-paul** [comment]
You should specify columns manually for such case instead of relying on `guessColumns()`.
There is no way to "guess" the column list for the headers rendering from the empty dataset.
