### ISSUE TITLE
Send exported file to browser

### ISSUE THREAD

**Issue by jeroenk22** [yii2tech/csv-grid#4]
Hello Paul,

Is there a way to send the downloaded file to the browser, so the user can decide where to save it?
I hope you can provide me some help.

Thanks in advance.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/web/Response.php#L456

**Comment by klimov-paul** [comment]
https://github.com/yii2tech/csv-grid/blob/master/ExportResult.php#L199

**Comment by wingsryder** [comment]
Here is what I am using to have it download on browser. 

if (file_exists($source_directory.$fileName)){
        return Yii::$app->response->sendFile($source_directory.$fileName);
  }
