### ISSUE TITLE
Call to a member function renderHeaderCellContent() on array

### ISSUE THREAD

**Issue by sadam-sds** [yii2tech/csv-grid#5]
Error Exception occurs when no data record against the query. 

PHP Fatal Error – yii\base\ErrorException

Call to a member function renderHeaderCellContent() on array

391392393394395396397398399400401402403404405406407408409 
    /**
     * Composes header row contents.
     * @return array cell contents.
     */
    protected function composeHeaderRow()
    {
        $cells = [];
        foreach ($this->columns as $column) {
            $cells[] = $column->renderHeaderCellContent();
        }
        return $cells;
    }
 
    /**
     * Composes header row contents.
     * @return array cell contents.
     */
    protected function composeFooterRow()

**Comment by klimov-paul** [comment]
Unable to reproduce.
Empty data use case is covered by unit test:
https://github.com/yii2tech/csv-grid/blob/master/tests/CsvGridTest.php#L143-L168
