### ISSUE TITLE
Issue in writing HTML data  to CSV sheet

### ISSUE THREAD

**Issue by wingsryder** [yii2tech/csv-grid#8]
I have a textarea field for capturing content that accept HTML.

On printing array value (using die) this field render cell content as HTML  very well (with p , br tags) [Attached Screenshot]

Now when this content data written in CSV this will be writing in HTML_ENCODE Format . There is no such code added to do the formatting. I need the complete HTML written in content field to get exported to sheet.

**Controller Code  :**
----------------------

```
 $productData= [];
 $comments = $dataItems->comments;			
 $productData['comments'] = $comments;

  $exporter = new CsvGrid([
            /* 'csvFileConfig' => [
              'cellDelimiter' => "\t",
              'rowDelimiter' => "\n",
              'enclosure' => '',
              ], */


            'dataProvider' => new ArrayDataProvider([
                'allModels' => $csvdata,
                    ]),
            'columns' => [			
                [ 'attribute' => 'comments', 'label' => 'comments'],
            ],
        ]);
		
        $source_directory = Yii::$app->basePath . \Yii::$app->params['web.upload.path'] . "/uploads/";
        $status = $exporter->export()->saveAs($source_directory . $file);

```

Any one facing same ? Any formatting need to add?
![bug](https://user-images.githubusercontent.com/1322917/27336922-9f851192-55ee-11e7-9017-50c64ee4a6fd.png)

**Comment by wingsryder** [comment]
**UPDATE  :**   This is not Extension Bug.

I have fixed it using  [ 'attribute' => 'comments', 'label' => 'comments' , 'format' => 'html'],

**Comment by cronfy** [comment]
@klimov-paul Just to clarify this - why default format is 'text' and not 'raw'?

**Comment by klimov-paul** [comment]
0eed9561e878f16d57b5b560e7353e9452297763
